config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resource :session
  resources :passwords, param: :token
  
  resources :tasks do
    resources :messages
  end

  resource :unsubscribe, only: [ :show ]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  resources :products do 
    resources :subscribers, only: [ :create ]
  end

  # Defines the root path route ("/")
  root "tasks#index"
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :task
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: %i[ show edit update destroy ]
  before_action :set_task

  # GET /messages or /messages.json
  # def index
  #   @messages = Message.all
  # end

  # # GET /messages/1 or /messages/1.json
  # def show
  # end

  # GET /messages/new
  # def new
  #   @message = Message.new
  # end

  # GET /messages/1/edit
  # def edit
  # end

  # POST /messages or /messages.json
  def create
    # debug
    @message = @task.messages.create(message_params)
    @message.user = Current.user
    

    respond_to do |format|
      if @message.save
        format.html { redirect_to task_path(@task), notice: "Message was successfully created." }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1 or /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: "Message was successfully updated." }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1 or /messages/1.json
  def destroy
    @message.destroy!

    respond_to do |format|
      format.html { redirect_to messages_path, status: :see_other, notice: "Message was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task 
      @task ||= Task.find(params[:task_id])
    end

    # def set_message
    #   @message = Message.find(params.expect(:id))
    # end

    # Only allow a list of trusted parameters through.
    def message_params
      params.expect(message: [ :content])
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= form_with(model: message, html: { contents: true }) do |form| %>
  <% if message.errors.any? %>
    <div class="alert alert--negative flex flex-col gap-half mbe-4" role="alert">
      <h2 class="font-medium leading-none"><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul class="text-sm mis-3" style="list-style: disc">
        <% message.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="flex flex-col gap-half mbe-4">
    <%= form.label :content, class: "text-sm font-medium leading-none" %>
    <%= form.textarea :content, rows: "auto", class: "input" %>
  </div>

  <div class="flex flex-col gap-half mbe-4">
    <%= form.label :user_id, class: "text-sm font-medium leading-none" %>
    <%= form.text_field :user_id, class: "input" %>
  </div>

  <div class="flex flex-col gap-half mbe-4">
    <%= form.label :task_id, class: "text-sm font-medium leading-none" %>
    <%= form.text_field :task_id, class: "input" %>
  </div>

  <div class="inline-flex items-center mbs-2 mie-1">
    <%= form.submit class: "btn btn--primary" %>
  </div>
<% end %>

app/views/messages/_message.html.erb
<div id="<%= dom_id message %>" class="flex flex-col gap">
  <div class="flex flex-col gap-half">
    <h4 class="font-medium leading-none">Content:</h4>
    <p class="leading-none"><%= message.content %></p>
  </div>
  <div class="flex flex-col gap-half">
    <h4 class="font-medium leading-none">User:</h4>
    <p class="leading-none"><%= message.user.email_address %></p>
  </div>
  <div class="flex flex-col gap-half">
    <h4 class="font-medium leading-none">Time</h4>
    <p class="leading-none"><%= message.created_at %></p>
  </div>
</div>

app/views/messages/edit.html.erb
<% content_for :title, "Editing message" %>

<h1 class="font-bold text-4xl mbe-4">Editing message</h1>

<%= render "form", message: @message %>

<div class="inline-flex flex-wrap items-center gap mbs-2" style="--row-gap: .5rem">
  <%= link_to "Show this message", @message, class: "btn" %>
  <%= link_to "Back to messages", messages_path, class: "btn" %>
</div>

app/views/messages/index.html.erb
<% if notice.present? %>
  <div popover class="flash" style="--flash-position: 5rem;" data-controller="element-removal" data-action="animationend->element-removal#remove" role="alert"><%= notice %></div>
<% end %>

<% content_for :title, "Messages" %>

<div class="flex items-center justify-between mbe-4">
  <h1 class="font-bold text-4xl">Messages</h1>
  <%= link_to "New message", new_message_path, class: "btn btn--primary" %>
</div>

<div id="messages" class="flex flex-col" style="gap: 2rem;">
  <% @messages.each do |message| %>
    <div class="flex flex-col items-start gap">
      <%= render message %>
      <%= link_to "Show this message", message, class: "btn" %>
    </div>
  <% end %>
</div>

app/views/messages/new.html.erb
<% content_for :title, "New message" %>

<h1 class="font-bold text-4xl mbe-4">New message</h1>

<%= render "form", message: @message %>

<div class="inline-flex flex-wrap items-center gap mbs-2" style="--row-gap: .5rem">
  <%= link_to "Back to messages", messages_path, class: "btn" %>
</div>

app/views/messages/show.html.erb
<% if notice.present? %>
  <div popover class="flash" style="--flash-position: 5rem;" data-controller="element-removal" data-action="animationend->element-removal#remove" role="alert"><%= notice %></div>
<% end %>

<%= render @message %>

<div class="flex flex-wrap items-center gap mbs-6" style="--row-gap: .5rem">
  <%= link_to "Edit this message", edit_message_path(@message), class: "btn" %>
  <%= link_to "Back to messages", messages_path, class: "btn" %>
  <%= button_to "Destroy this message", @message, method: :delete, class: "btn" %>
</div>